name: Metrics

on:  
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: 
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: KvaleroSor
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          #plugin_activity: yes
          plugin_github: yes
          plugin_repositories: yes
          plugin_languages: yes
          plugin_lines: yes
          

      
