name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Classic Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: KvaleroSor
          template: classic
          base: ""
          output: "github-metrics.svg"

      - name: Generate Isometric Commit Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: KvaleroSor
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          output: "metrics.plugin.isocalendar.svg"

      - name: Generate Languages Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: KvaleroSor
          plugin_languages: yes
          output: "metrics.plugin.languages.svg"

      - name: Generate Repositories Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: KvaleroSor
          plugin_repositories: yes
          output: "metrics.plugin.repositories.svg"





          

      
